### ISSUE TITLE
Move strings and constants to config file

### ISSUE THREAD

**Issue by minhnh** [HBRS-SDP/ws23-feedback-pouring#19]
I would move the hard-coded strings and number to a configuration file, e.g. using [`libconfig`](https://hyperrealm.github.io/libconfig/libconfig_manual.html).

https://github.com/HBRS-SDP/ws23-feedback-pouring/blob/4a1b2eb526d130a04f92bbcef825ab43c9808a17/feedback_pouring/src/kdl_with_pouring.cpp#L112

**Comment by vickyprince** [comment]
Done
PR - https://github.com/HBRS-SDP/ws23-feedback-pouring/pull/25
