### ISSUE TITLE
Setting-up the Kinova Arm

### ISSUE THREAD

**Issue by pallaviaithalnarayan** [HBRS-SDP/ws23-feedback-pouring#2]

**Comment by vickyprince** [comment]
Dismantled Kinova ARM from Freddy and mounted it on the table with gripper

**Comment by pallaviaithalnarayan** [comment]
https://www.kinovarobotics.com/uploads/User-Guide-Gen3-R07.pdf

**Comment by pallaviaithalnarayan** [comment]
closing this issue, as it was created for the project board reference.
It is present in Project board.
