### ISSUE TITLE
Choosing the control mode ( Velocity / Torque )

### ISSUE THREAD

**Issue by pallaviaithalnarayan** [HBRS-SDP/ws23-feedback-pouring#6]

**Comment by pallaviaithalnarayan** [comment]
Considering the velocity control mode

**Comment by minhnh** [comment]
I would close the issues that are marked as done. I would link PR's to the issues that they resolve, whenever possible. What that also means is that issues should be planned to be resolved with a PR at some point.

**Comment by pallaviaithalnarayan** [comment]
This is not an issue, since it was created for the project board reference.
The task exists in Project board. We will keep the issues linked to the PR from now on.
